name: 'TechStock — Local'
values:
  - key: baseUrl
    value: 'http://localhost:4000/api/v1'
    enabled: true
    type: default
  - key: deviceId
    value: 'postman-device-01'
    enabled: true
    type: default
  - key: accessToken
    value: ''
    enabled: true
    type: secret
  - key: refreshToken
    value: ''
    enabled: true
    type: secret
  - key: categoryId
    value: ''
    enabled: true
    type: default
  - key: supplierId
    value: ''
    enabled: true
    type: default
  - key: productId
    value: ''
    enabled: true
    type: default
  - key: productBarcode
    value: ''
    enabled: true
    type: default
  - key: customerId
    value: ''
    enabled: true
    type: default
  - key: saleId
    value: ''
    enabled: true
    type: default
  - key: saleItemId
    value: ''
    enabled: true
    type: default
  - key: purchaseOrderId
    value: ''
    enabled: true
    type: default
  - key: purchaseItemId
    value: ''
    enabled: true
    type: default
  - key: expenseId
    value: ''
    enabled: true
    type: default
